# name: Publish Docker

# on:
#   push:
#     branches: [master]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - name: Publish to registy
#         uses: elgohr/Publish-Docker-Github-Action@v4
#         with:
#           registry: docker.pkg.github.com
#           name: docker.pkg.github.com/stats21220/backend_mdvlad/mdvlad
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#           tags: 'develop'

- name: Build and push Docker image
  uses: docker/build-push-action@dckr_pat_Kofmcl79RWw7oIRR9L17QkwX6TQ
  with:
    context: .
    file: ./Dockerfile
    platforms: ${{ matrix.platforms }}
    push: true
    outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=My multi-arch image
